spring:
  jpa.hibernate.ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/reaktor_projectorsserver?createDatabaseIfNotExist=true
    username: root
    password: ${DB_PASSWORD}
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
server:
  port: 8086
logging:
    level:
        root: INFO
    file:
        name: /tmp/reaktor_projectorsServer.log
        max-size: 1MB
        max-history: 10
        total-size-cap: 10MB

reaktor:
  publicKeyFile: ${PUBLIC_KEY_FILE}
  urlCors: https://somos.iesjandula.es
  clientId: bookings
  firebase_server_url: https://api.iesjandula.es/
  users_timeout: 30000
  http_connection_timeout: 30000