spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/reaktor_projectorsserver?createDatabaseIfNotExist=true
    username: root
    password: toor
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5

server:
  port: 8086

logging:
  level:
    root: INFO
    es.iesjandula: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: proyectores.log
  logback:
    rollingpolicy:
      max-size: 1MB
      max-history: 20
      total-size-cap: 10MB

reaktor:
  publicKeyFile: /home/jaydee/.openssl/public_key.pem
  privateKeyFile: /home/jaydee/.openssl/private_key.pem
  googleCredentialsFile: /home/jaydee/.openssl/firebaseGoogleCredentials.json
  urlCors: http://localhost:5173, http://192.168.1.209:5173
