spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/proyectores
    username: root
    password: 1234
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5

server:
  port: 8085

logging:
  level:
    root: INFO # Ensures all logs are visible in the console
    es.iesjandula: INFO # Your specific package logs will be in DEBUG mode
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" # Console log format
  file:
    name: proyectores.log
  logback:
    rollingpolicy:
      max-size: 1MB
      max-history: 20
      total-size-cap: 10MB
